// In-memory resilient dev store for Admin Panel when DATABASE_URL is not set

export const mockAdminDb = {
  users: [
    {
      id: 'usr_001',
      full_name: 'Navin Chakraborty',
      email: 'navi@kepwe.com',
      mobile: '+91 98765 43210',
      role: 'user',
      plan: 'Pro Member',
      is_active: true,
      email_verified: true,
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      last_login_at: new Date().toISOString(),
      company_name: 'Acme Innovations Pvt Ltd',
      risk_category: 'moderate',
    },
    {
      id: 'usr_002',
      full_name: 'Aditi Sharma',
      email: 'aditi.sharma@techcorp.in',
      mobile: '+91 98111 22334',
      role: 'user',
      plan: 'Enterprise VIP',
      is_active: true,
      email_verified: true,
      created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
      last_login_at: new Date(Date.now() - 3600000).toISOString(),
      company_name: 'TechCorp Logistics',
      risk_category: 'low',
    },
    {
      id: 'usr_003',
      full_name: 'Rahul Verma',
      email: 'rahul.v@apexglobal.com',
      mobile: '+91 99887 76655',
      role: 'user',
      plan: 'Pro Member',
      is_active: true,
      email_verified: true,
      created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      last_login_at: new Date(Date.now() - 7200000).toISOString(),
      company_name: 'Apex Global Media',
      risk_category: 'high',
    },
    {
      id: 'usr_004',
      full_name: 'Priya Patel',
      email: 'priya@patelconsulting.com',
      mobile: '+91 97654 32109',
      role: 'user',
      plan: 'Free Trial',
      is_active: true,
      email_verified: true,
      created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      last_login_at: new Date().toISOString(),
      company_name: 'Patel Legal Advisory',
      risk_category: 'conservative',
    },
    {
      id: 'usr_005',
      full_name: 'Siddharth Rao',
      email: 'sid.rao@quantfin.io',
      mobile: '+91 91234 56780',
      role: 'user',
      plan: 'Enterprise VIP',
      is_active: true,
      email_verified: true,
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      last_login_at: new Date().toISOString(),
      company_name: 'QuantFin Capital',
      risk_category: 'aggressive',
    },
  ],

  plans: [
    { id: 'plan_1', name: 'Free Trial', display_name: 'Free Starter Tier', price_inr: 0, interval: 'month', is_active: true },
    { id: 'plan_2', name: 'Pro Member', display_name: 'Pro Algorithmic & Ledger', price_inr: 4999, interval: 'month', is_active: true },
    { id: 'plan_3', name: 'Enterprise VIP', display_name: 'Enterprise Advisory & Execution', price_inr: 14999, interval: 'month', is_active: true },
  ],

  subscriptions: [
    {
      id: 'sub_001',
      user_id: 'usr_001',
      user_name: 'Navin Chakraborty',
      user_email: 'navi@kepwe.com',
      full_name: 'Navin Chakraborty',
      email: 'navi@kepwe.com',
      plan_name: 'Pro Member',
      display_name: 'Pro Algorithmic & Ledger',
      status: 'active',
      price: 4999,
      price_at_signup: 4999,
      billing_interval: 'month',
      current_period_end: new Date(Date.now() + 20 * 86400000).toISOString(),
      renews_on: new Date(Date.now() + 20 * 86400000).toISOString(),
      payment_method: 'Razorpay / UPI',
      auto_renew: true,
      created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'sub_002',
      user_id: 'usr_002',
      user_name: 'Aditi Sharma',
      user_email: 'aditi.sharma@techcorp.in',
      full_name: 'Aditi Sharma',
      email: 'aditi.sharma@techcorp.in',
      plan_name: 'Enterprise VIP',
      display_name: 'Enterprise Advisory & Execution',
      status: 'active',
      price: 14999,
      price_at_signup: 14999,
      billing_interval: 'month',
      current_period_end: new Date(Date.now() + 15 * 86400000).toISOString(),
      renews_on: new Date(Date.now() + 15 * 86400000).toISOString(),
      payment_method: 'NetBanking',
      auto_renew: true,
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],

  payments: [
    {
      id: 'pay_001',
      invoice_number: 'INV-2026-001',
      user_name: 'Navin Chakraborty',
      user_email: 'navi@kepwe.com',
      full_name: 'Navin Chakraborty',
      email: 'navi@kepwe.com',
      amount: 4999,
      status: 'Paid',
      plan_name: 'Pro Member',
      billing_date: new Date().toISOString().split('T')[0],
      method: 'Razorpay / UPI',
      payment_method: 'Razorpay / UPI',
      created_at: new Date().toISOString(),
    },
    {
      id: 'pay_002',
      invoice_number: 'INV-2026-002',
      user_name: 'Aditi Sharma',
      user_email: 'aditi.sharma@techcorp.in',
      full_name: 'Aditi Sharma',
      email: 'aditi.sharma@techcorp.in',
      amount: 14999,
      status: 'Paid',
      plan_name: 'Enterprise VIP',
      billing_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      method: 'NetBanking',
      payment_method: 'NetBanking',
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
  ],

  crmLeads: [
    {
      id: 'lead_001',
      name: 'Vikas Malhotra',
      contact_name: 'Vikas Malhotra',
      company_name: 'Malhotra Infotech',
      email: 'vikas@malhotragroup.in',
      mobile: '+91 98222 33445',
      company: 'Malhotra Infotech',
      service_interest: 'Accounting & Ledger Platform',
      status: 'New',
      lead_score: 'HOT',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'lead_002',
      name: 'Sneha Roy',
      contact_name: 'Sneha Roy',
      company_name: 'FinTech Labs India',
      email: 'sneha@fintechlab.co',
      mobile: '+91 98333 44556',
      company: 'FinTech Labs India',
      service_interest: 'Virtual CFO Advisory',
      status: 'Connected',
      lead_score: 'WARM',
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],

  announcements: [
    {
      id: 'ann_001',
      title: 'KEPWE Ledger Live Release v2.0',
      message: 'Full-featured financial management platform is now live for all enterprise users.',
      target_audience: 'all',
      is_active: true,
      placement: 'all',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],

  auditLogs: [
    {
      id: 'log_001',
      admin_name: 'KEPWE Super Admin',
      username: 'admin',
      display_name: 'KEPWE Super Admin',
      action: 'admin.signin',
      entity_type: 'AUTH',
      entity_id: 'admin_root_dev',
      metadata: { ip: '127.0.0.1', environment: 'development' },
      details: 'Administrator signed in from local dev console',
      created_at: new Date().toISOString(),
    },
    {
      id: 'log_002',
      admin_name: 'System',
      username: 'system',
      display_name: 'System Engine',
      action: 'ledger.reconcile',
      entity_type: 'FINANCE',
      entity_id: 'system',
      metadata: { accountsSynced: 6, status: 'SUCCESS' },
      details: 'Automated ledger balance synchronization completed',
      created_at: new Date(Date.now() - 3600000).toISOString(),
    },
  ],

  notifications: [
    {
      id: 'notif_001',
      type: 'registration',
      title: 'New Account Created',
      message: 'Navin Chakraborty signed up for Pro Member plan.',
      is_read: false,
      created_at: new Date().toISOString(),
    },
    {
      id: 'notif_002',
      type: 'payment',
      title: 'Payment Received',
      message: '₹14,999 received from TechCorp Logistics.',
      is_read: true,
      created_at: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};

export function getMockAdminDashboard(range = '30d') {
  return {
    stats: {
      totalUsers: mockAdminDb.users.length + 137,
      newAccounts: 28,
      activeUsers: 64,
      totalSubscriptions: 96,
      activeSubscriptions: 82,
      revenue: 384500,
      range,
    },
    recentRegistrations: mockAdminDb.users.slice(0, 5),
    recentActivity: [
      { type: 'login', full_name: 'Navin Chakraborty', email: 'navi@kepwe.com', occurred_at: new Date().toISOString() },
      { type: 'purchase', full_name: 'Aditi Sharma', email: 'aditi.sharma@techcorp.in', occurred_at: new Date(Date.now() - 3600000).toISOString() },
      { type: 'login', full_name: 'Rahul Verma', email: 'rahul.v@apexglobal.com', occurred_at: new Date(Date.now() - 7200000).toISOString() },
    ],
    planBreakdown: [
      { plan: 'Pro Member', display_name: 'Pro Algorithmic & Ledger', count: 48 },
      { plan: 'Enterprise VIP', display_name: 'Enterprise Advisory & Execution', count: 24 },
      { plan: 'Free Trial', display_name: 'Free Starter Tier', count: 24 },
    ],
    recentPayments: mockAdminDb.payments,
    loginHistory: [
      { id: 'sess_1', full_name: 'Navin Chakraborty', email: 'navi@kepwe.com', user_agent: 'Chrome / Windows', ip_address: '127.0.0.1', created_at: new Date().toISOString() },
    ],
  };
}

export function getMockRevenueAnalytics(range = '30d') {
  return {
    range,
    daily: [
      { period: '2026-08-28', revenue: 14999 },
      { period: '2026-08-29', revenue: 24998 },
      { period: '2026-08-30', revenue: 19999 },
      { period: '2026-08-31', revenue: 29999 },
      { period: '2026-09-01', revenue: 34999 },
    ],
    weekly: [
      { period: '2026-08-10', revenue: 65000 },
      { period: '2026-08-17', revenue: 98000 },
      { period: '2026-08-24', revenue: 135000 },
      { period: '2026-08-31', revenue: 86500 },
    ],
    monthly: [
      { period: '2026-06', revenue: 180000 },
      { period: '2026-07', revenue: 245000 },
      { period: '2026-08', revenue: 384500 },
    ],
    activeSubscriptions: mockAdminDb.subscriptions.length + 80,
    trialToPaidConversion: 42.5,
  };
}
